services:
  - type: web
    name: WEBTOR
    env: python
    buildCommand: bash run.sh
    startCommand:  bash run.sh
    repo: https://github.com/sholoomail/WEBTOR.git
    branch: main
    envVars:
      - key: AUTH 
        sync: false
